### ISSUE TITLE
v5.05 and may be v5.04 breaks many modules

### ISSUE THREAD

**Issue by Perlover** [kentfredric/HTML-Tree#1]
Hi,

I found 100% problem from your v5.05 version with Web::Scrapper
Same errors;

Examples:
http://www.cpantesters.org/cpan/report/78ead4ae-2664-11e7-b625-8b3bdc40f832
http://www.cpantesters.org/cpan/report/7812f82c-2664-11e7-b625-8b3bdc40f832
http://www.cpantesters.org/cpan/report/77400106-2664-11e7-b625-8b3bdc40f832

I installed v5.03 and everything was fine

And other module:
https://rt.cpan.org/Ticket/Display.html?id=121310

Please check up please as soon as and patch it!

Best regards, Perlover

**Comment by kentfredric** [comment]
I've published 5.06 which has the offending changes backed out until a non-breaking strategy to do the same can be found.

Thanks.

**Comment by oschwald** [comment]
I believe the `Web::Scraper` issue is caused by `HTML::TreeBuilder::XPath`'s monkey patching of this module. I created [a ticket there](https://rt.cpan.org/Public/Bug/Display.html?id=121360) when we ran into the issue after upgrading `HTML::Tree` to 5.04.

**Comment by Perlover** [comment]
No, I thought same to
But the HTML::TreeBuilder::XPath is old
But I installed many times near year and all was fine

When I installed 5.03 problems are gone


28 Апр 2017 г. 15:28 пользователь "Gregory Oschwald" <
notifications@github.com> написал:

I believe the Web::Scraper issue is caused by HTML::TreeBuilder::XPath's
monkey patching of this module. I created a ticket there
<https://rt.cpan.org/Public/Bug/Display.html?id=121360> when we ran into
the issue after upgrading HTML::Tree to 5.04.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kentfredric/HTML-Tree/issues/1#issuecomment-297997633>,
or mute the thread

**Comment by kentfredric** [comment]
Fwiw, the breaking behaviour is still in the dev release, just in case this is a problem consumers can be expected to fix.

But I don't fully understand the issue yet, so I've just reverted the change in the stable release until then.

**Comment by oschwald** [comment]
@Perlover, I agree that the upgrade to `HTML::Tree` caused the issue, but that is because monkey patching in the way that `HTML::TreeBuilder::XPath` does it is extremely fragile. For instance, `HTML::Tree` 5.04 added `_xml_escape_text`, which [the monkeypatch](https://metacpan.org/source/HTML::TreeBuilder::XPath#L97) already defined.
